### ISSUE TITLE
Return to Gloom Hollow LUA Error

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#117] opened 2018-02-12 22:36 UTC
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> LUA error appeared while doing the quest

**Details:**
> Went into the statue, walked a couple meters and an LUA error popped up without doing anything : 
https://i.imgur.com/PkYeeFj.jpg

Message: Interface\FrameXML\ChatFrame.lua:3366: bad argument #3 to 'format' (number expected, got string)
Time: Mon Feb 12 19:44:35 2018
Count: 1
Stack: Interface\FrameXML\ChatFrame.lua:3366: bad argument #3 to 'format' (number expected, got string)
[C]: ?
[C]: in function `format'
Interface\FrameXML\ChatFrame.lua:3366: in function `ChatFrame_MessageEventHandler'
Interface\FrameXML\ChatFrame.lua:2787: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: 

**Reproducible:**
> Don't know

**Howto:**
> Take Return to Gloom Hollow, jump into the statue, walk

**Comment by Melekus** [comment] 2018-02-12 22:54
Duplicate of #23

**Closed by Melekus** 2018-02-12 22:54 UTC
Labels: 1-BfA, Quest, Quest: Horde
