### ISSUE TITLE
[Mage] Frozen Orb not stopping in position when coming in to contact with monsters.

### ISSUE THREAD

**Issue by Glynnyx** [SimCMinMax/WoW-BugTracker#278] opened 2018-06-08 08:05 UTC
**Game Version:**
> 8.0.1 Beta Build 26788

**Description:**
>Frozen Orb passing through monsters it comes in to contact with (similar to Legion)

**Details:**
>When aiming Frozen Orb towards a mob, it will deal damage to the mob put pass through it and not stay in that location as its supposed to.

**Logs, Images, Videos**
>Reported by a member of the Mage Discord, no proof provided but posting for visibility. The user mentioned he will provide evidence later.

**Reproducible:**
>Rarely, the user reported this happens 50% of the time.

**Howto:**
>Explained in details section

**Comment by vituscze** [comment] 2018-06-08 08:07
Duplicate of #272

**Closed by vituscze** 2018-06-08 08:07 UTC
Labels: 1-BfA, Mage: Frost
