### ISSUE TITLE
No Complete Quest marker for Bullwark of Torcali

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#192] opened 2018-03-03 10:25 UTC
**Game Version:**
> 8.0.1 Alpha Build 26141

**Description:**
> We don't know where to give back the quest after completing it

**Details:**
> After completion, we are not going out of the vehicule automatically. When going out manually, when then have no marker on the map to see where to complete the quest

**Logs, Images, Videos**
> https://i.imgur.com/aWlf8my.jpg

**Reproducible:**
> 100%

**Howto:**
> Have Bullwark of Torcali
> destroy enemies
> get out of vehicule
> no quest complete marker on the map

**Comment by Mystler** [comment] 2018-03-03 11:27
Duplicate of https://github.com/SimCMinMax/WoW-BugTracker/issues/172.

**Closed by Mystler** 2018-03-03 11:27 UTC
Labels: 1-BfA, Quest, Quest: Horde
