### ISSUE TITLE
Heal estimator is very off

### ISSUE THREAD

**Issue by Zarania** [SimCMinMax/WoW-BugTracker#83] opened 2018-02-10 05:56 UTC
**Game Version:**
8.0.1 Alpha Build 25976

**Description:**
The healing estimator shows the healing a lot larger than happens

![image](https://user-images.githubusercontent.com/8323677/36059008-a6fbc21a-0dfc-11e8-9441-4b27f1106dd0.png)

![image](https://user-images.githubusercontent.com/8323677/36059011-b19b0c58-0dfc-11e8-89ab-38e5496502aa.png)

**Reproducible:**
Yes

**Howto:**
Cast healing surge

**Comment by Aethys256** [comment] 2018-02-10 05:59
Duplicate of https://github.com/SimCMinMax/WoW-BugTracker/issues/20

**Closed by Aethys256** 2018-02-10 05:59 UTC
Labels: Shaman, Shaman: Elemental, Shaman: Enhancement, Shaman: Restoration, UI
