### ISSUE TITLE
Crimson Tempest does not proc Elaborate Planning

### ISSUE THREAD

**Issue by Kiwifruity** [SimCMinMax/WoW-BugTracker#103] opened 2018-02-12 01:38 UTC
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Elaborate planning is supposed to proc when a finisher is used, but does not proc when crimson tempest is used

**Reproducible:**
> 100%

**Howto:**
> Talent elaborate planning, use crimson tempest

**Comment by Zarania** [comment] 2018-02-12 03:06
Duplicate of #75

**Closed by Zarania** 2018-02-12 03:06 UTC
Labels: 1-BfA, Rogue, Rogue: Assassination
