### ISSUE TITLE
Shadow Mend healing prediction wrong

### ISSUE THREAD

**Issue by N1gh7h4wk** [SimCMinMax/WoW-BugTracker#112] opened 2018-02-12 12:28 UTC
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> Healing Prediction for Shadow Mend in at least Shadow Specialization

**Details:**
> The Healing Prediction predicts too much healing

**Reproducible:**
> yes

**Howto:**
> cast Shadow Mend, look at your Healing Prediction bar

**Comment by Bloodmallet** [comment] 2018-02-12 12:40
Duplicate of #20

**Closed** 2018-02-12 12:39 UTC
Labels: 1-BfA, Priest, Priest: Shadow, UI
