### ISSUE TITLE
Deathly Shadows Legendary works in all 3 specializations of Rogue

### ISSUE THREAD

**Issue by ZeraTheRedRogue** [SimCMinMax/WoW-BugTracker#667] opened 2020-09-20 23:49 UTC
**Game Version:**
> 9.0.2 beta Build 35938

**Description:**
> The Subtlety rogue legendary "Deathly Shadows" works in all 3 specializations of rogue. This honestly should be a generic legendary, as a simple Vanish interaction makes sense to be utilized by all 3, however with the recent hotfix to the outlaw legendary Celerity which was functioning in all 3 specs, it is plausible this will also be changed in the future.

**Reproducible:**
> Yes

**Howto:**
> Equip Deathly Shadows. Use vanish or sepsis in any of the 3 specializations of rogue. Observe damage boost and free 5 combo points.

**Comment by Mystler** [comment] 2020-11-05 13:04
Still the case in 36512. Intended? Waiting for end of beta to decide if we wanna close this as wontfix.

**Comment by Lorentz21** [comment] 2020-12-08 08:49
Pretty much confirmed as intended, hotfixed on 1st of December so that any specialization can craft this legendary

**Comment by Mystler** [comment] 2020-12-19 00:24
Changed to be fully intended. Closing.

**Closed by Mystler** 2020-12-19 00:24 UTC
Labels: 0-Beta, 2-Shadowlands, Rogue, Rogue: Assassination, Rogue: Outlaw, Rogue: Subtlety
