### ISSUE TITLE
Chain reaction stacks on targets that arent frozen

### ISSUE THREAD

**Issue by Juliacare** [SimCMinMax/WoW-BugTracker#276] opened 2018-06-04 17:00 UTC
**Game Version:**
> 8.0.1 Beta Build 26734

**Description:**
> What is your bug about?
Frost mage talent Chain Reaction gains stacks from normal unbuffed icelances

**Details:**
> Try to explain the bug.
The talent should only add stacks when icelance is used on a frozen target. It does it regardless now.

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug.
https://youtu.be/ap2NT2IO414

**Reproducible:**
> Examples: yes

**Howto:**
> How do you reproduce it (if you know).
You press icelance on a target and you get the buff. Relogged and relaunched, even created a new mage. It worked on all 4 mentioned scenario's.

**Comment by vituscze** [comment] 2018-06-04 17:15
Duplicate of #264

**Closed by vituscze** 2018-06-04 17:15 UTC
