### ISSUE TITLE
Mindebender Talent is not working properly

### ISSUE THREAD

**Issue by Tohrka** [SimCMinMax/WoW-BugTracker#950] opened 2022-09-27 20:03 UTC
**Game Version:**
> 10.0.2 beta Build 45746

**Description:**
> When you skill mindbender in the Talenttree the ability still shows as shadowfiend and has a 3 min cooldown

**Logs, Images, Videos**
> Please attach Logs, Images, and/or a Video of the bug if applicable.

**Reproducible:**
> Examples: yes

**Howto:**
> choose the mindbender talent
![shadow mindbender bug 3](https://user-images.githubusercontent.com/84905369/192624167-69bfbb05-d8b2-4ddd-927a-02ec9b52df84.png)
![shadow mindbender bug1](https://user-images.githubusercontent.com/84905369/192624180-ea1f026b-d045-4567-985f-728ec5fb351f.png)
![shadow mindbender bug 2](https://user-images.githubusercontent.com/84905369/192624185-d0f88da9-4004-427c-af4c-1499e2e85729.png)

**Comment by seanpeters86** [comment] 2022-09-29 01:58
was not able to reproduce, closing until more data is provided. Try making a new character

**Closed by seanpeters86** 2022-09-29 01:58 UTC
Labels: 0-Beta, 2-Dragonflight
