### ISSUE TITLE
Voidling glyph shadowfiend 

### ISSUE THREAD

**Issue by sanderhiemstra** [SimCMinMax/WoW-BugTracker#1039] opened 2022-10-26 21:22 UTC
When you apply Voidling glyph Shadowfiend Mindbender nolonger overrides it so it will stay at a 3 minute cooldown

**Comment by seanpeters86** [comment] 2022-10-27 15:10
duplicate of https://github.com/SimCMinMax/WoW-BugTracker/issues/1035

**Closed by seanpeters86** 2022-10-27 15:10 UTC
