### ISSUE TITLE
Soul of the Deathlord gives the wrong talent in for Frost

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/WoW-BugTracker#96] opened 2018-02-11 10:46 UTC
**Game Version:**
> 8.0.1 Alpha Build 25976

**Description:**
> The legendary talent ring Soul of the Deathlord gives the Frostscythe talent instead of the Gathering Storm talent

**Details:**
> I believe it is because of the talent swaps in this row : Frostscythe is on the left and Gathering storm on the right on Live, and they are inverted in BfA Alpha. On the other hand, Bursting Sores (unholy talent) and Foul bulwark (blood talent) weren't swapped with any talent and are correctly given by the Soul of the Deathlord when equipped in the right spec.
Similar to the mage and rogue issues ( respectively #72 and #85 )

**Reproducible:**
> Yes

**Howto:**
> Buy the legendary ring off a vendor

**Comment by Bloodmallet** [comment] 2018-02-11 10:49
I think this is happening for every spec that now has these talent shuffles or new talents where the old one was.

**Comment by Aethys256** [comment] 2018-02-11 10:52
Think we should rather make an issue that ref all those things. So it's only in one place and avoid duplication since the root of the issue is the same.

**Comment by Bloodmallet** [comment] 2018-02-11 10:56
#85 #72 these are the other two. Which one should stay?

**Comment by Aethys256** [comment] 2018-02-11 10:58
IMO, make a new generic one that explains the root of the bug (i.e. that the talent ring gives talent based on talent X & Y position rather than the spell itself).
And just ref all other 3 inside the post. Can do it later if no one did already though.

**Comment by RosvallM** [comment] 2018-02-12 12:28
General issue opened here: https://github.com/SimCMinMax/WoW-BugTracker/issues/97
Closed as duplicate.

**Closed** 2018-02-12 12:28 UTC
Labels: -Duplicate, 1-BfA, Death Knight, Death Knight: Frost
